# Extracted from: Chapter 87 — Distillation and Model Specialization
# Source: src/.../ch087-distillation.md   Tier: A
# Regenerate with: make code  (do not edit by hand)

"""Distil or serve the teacher? The arithmetic, including the break-even."""

TEACHER_PARAMS = 400e9
STUDENT_PARAMS = 8e9
REQUESTS_PER_DAY = 2e6
TOKENS_PER_REQUEST = 700
GPU_COST_PER_HOUR = 2.50
GPU_FLOPS, MFU = 1e15, 0.45

# Distillation setup: generate training data from the teacher, then train.
DISTILL_TOKENS = 5e9                 # generated by the teacher
STUDENT_TRAIN_TOKENS = 5e9


def serve_cost_per_day(params):
    flops = 2 * params * REQUESTS_PER_DAY * TOKENS_PER_REQUEST
    hours = flops / (GPU_FLOPS * MFU) / 3600
    return hours * GPU_COST_PER_HOUR


def one_off_cost():
    gen = 2 * TEACHER_PARAMS * DISTILL_TOKENS          # teacher generation
    train = 6 * STUDENT_PARAMS * STUDENT_TRAIN_TOKENS  # student training
    hours = (gen + train) / (GPU_FLOPS * MFU) / 3600
    return hours * GPU_COST_PER_HOUR, gen, train


teacher_day = serve_cost_per_day(TEACHER_PARAMS)
student_day = serve_cost_per_day(STUDENT_PARAMS)
setup, gen_flops, train_flops = one_off_cost()

print(f"serving {REQUESTS_PER_DAY:,.0f} requests/day at "
      f"{TOKENS_PER_REQUEST} tokens each\n")
print(f"{'option':<28} {'$/day':>10} {'$/year':>12}")
print(f"{'serve the teacher directly':<28} {teacher_day:>10,.0f} "
      f"{teacher_day * 365:>12,.0f}")
print(f"{'serve a distilled student':<28} {student_day:>10,.0f} "
      f"{student_day * 365:>12,.0f}")

print(f"\ndistillation setup cost: ${setup:,.0f}")
print(f"  teacher generation : {gen_flops:.2e} FLOPs "
      f"({gen_flops / (gen_flops + train_flops):.0%} of it)")
print(f"  student training   : {train_flops:.2e} FLOPs")

saving_per_day = teacher_day - student_day
breakeven = setup / saving_per_day
print(f"\nsaving: ${saving_per_day:,.0f}/day")
print(f"break-even: {breakeven:.1f} days")
print(f"first-year net: ${saving_per_day * 365 - setup:,.0f}")

# Where the ratio stops being worth it.
print(f"\n{'requests/day':>14} {'break-even (days)':>19}")
for rpd in (1e4, 1e5, 1e6, 1e7):
    t = 2 * TEACHER_PARAMS * rpd * TOKENS_PER_REQUEST / (GPU_FLOPS * MFU) / 3600 * GPU_COST_PER_HOUR
    s = 2 * STUDENT_PARAMS * rpd * TOKENS_PER_REQUEST / (GPU_FLOPS * MFU) / 3600 * GPU_COST_PER_HOUR
    print(f"{rpd:>14,.0f} {setup / (t - s):>19.1f}")

print("""
Note where the setup cost goes: the great majority is the TEACHER GENERATING
the training data, not training the student. That is the opposite of most
people's intuition and it has a practical consequence — the lever for reducing
distillation cost is generating fewer, better-chosen examples rather than
training the student more cheaply.

And the break-even column is the decision. At low volume the setup never pays
back and serving the teacher is correct; at high volume it pays back in days.
Distillation is a volume play, and below the crossover it is a way of spending
money to get a worse model.""")
